variables:
  TG_URL: 'https://api.telegram.org/<tg_bot_token_must_be_here>'

stages:
  - build
  - test
  - notify

build-backend-code-job:
  stage: build  
  only:
    changes:
    - backend/**/*
  script:
    - cd backend
    - mvn package
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
  cache:
    paths:
      - ${CI_PROJECT_DIR}/.m2/repository

semgrep-sast:
  stage: test
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
  variables:
    COMPILE: "false"
    SAST_JAVA_VERSION: 11
    MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
  needs:
    - build-backend-code-job

telegram-notification-backend:
  stage: notify
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /send notification/
  script:
    - 'curl --request POST --header "Content-Type: application/json" --data "{\"chat_id\": \"-1002185373712\", \"text\": \"Артем Кононюк собрал бэкенд приложение! Ссылка $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/download?job=$CI_JOB_NAME\"}" $TG_URL/sendMessage'
  needs:
    - build-backend-code-job
